### ISSUE TITLE
mock returns incorrect error data when error specified by type

### ISSUE THREAD

**Issue by bg-kurosawa** [webpay/webpay-mock#5]
webpay_stub(:charges, :create, error: :card_error, params: params)
returns error but error data doesn't have caused_by.

Therefore, sample code in bellow link cannot be tested correctly.
http://engineering.webpay.co.jp/2014/12/09/check-your-error-handling/

For example, if you test sample code with mock specified :card_error, it will handle as "Unknown error" because caused_by is nil.

We can workaround by to specify all fields to test a specific error.
```
webpay_stub(:charges, :create, params: params, response: card_error(
    message: "You must provide the card which is not expired",
    caused_by: "buyer",
    param: "exp_month",
    code: "invalid_expiry_month"
    ))
```
but tiresome :-(

**Comment by tomykaira** [comment]
Could you try the latest version 0.2.0?
